package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ReportCardAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportCardAllPropertiesEquals(ReportCard expected, ReportCard actual) {
        assertReportCardAutoGeneratedPropertiesEquals(expected, actual);
        assertReportCardAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportCardAllUpdatablePropertiesEquals(ReportCard expected, ReportCard actual) {
        assertReportCardUpdatableFieldsEquals(expected, actual);
        assertReportCardUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportCardAutoGeneratedPropertiesEquals(ReportCard expected, ReportCard actual) {
        assertThat(expected)
            .as("Verify ReportCard auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportCardUpdatableFieldsEquals(ReportCard expected, ReportCard actual) {
        assertThat(expected)
            .as("Verify ReportCard relevant properties")
            .satisfies(e -> assertThat(e.getSemester()).as("check semester").isEqualTo(actual.getSemester()))
            .satisfies(e -> assertThat(e.getClassification()).as("check classification").isEqualTo(actual.getClassification()))
            .satisfies(e -> assertThat(e.getPdfFile()).as("check pdfFile").isEqualTo(actual.getPdfFile()))
            .satisfies(
                e -> assertThat(e.getPdfFileContentType()).as("check pdfFile contenty type").isEqualTo(actual.getPdfFileContentType())
            )
            .satisfies(e -> assertThat(e.getComments()).as("check comments").isEqualTo(actual.getComments()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportCardUpdatableRelationshipsEquals(ReportCard expected, ReportCard actual) {}
}
